// Generated by https://quicktype.io

export interface Airport {
    id:               number;
    IATA:             string;
    name:             string;
    codeIso2Country:  string;
    ICAO:             string;
    IATACity:         string;
    latitude:         number;
    longitude:        number;
    timezone:         string;
    UTCOffset:        number;
    isRailRoad:       number;
    isBusStation:     number;
    nameTranslations: string;
    popularity:       number;
    phone:            string;
    website:          string;
    geoNameId:        number;
    routes:           number;
    country:          string;
}
