// Generated by https://quicktype.io

export interface TafData {
    Forecast:     TafForecast[];
    Info:         Info;
    "Max-Temp":   string;
    Meta:         Meta;
    "Min-Temp":   string;
    "Raw-Report": string;
    Remarks:      string;
    Station:      string;
    Time:         string;
    Translations: Translations;
    Units:        Units;
}

export interface TafForecast {
    Altimeter:        string;
    "Cloud-List":     Array<string[]>;
    "End-Time":       string;
    "Flight-Rules":   string;
    "Icing-List":     any[];
    "Other-List":     string[];
    Probability:      string;
    "Raw-Line":       string;
    "Start-Time":     string;
    Summary:          string;
    "Turb-List":      any[];
    Type:             string;
    Visibility:       string;
    "Wind-Direction": string;
    "Wind-Gust":      string;
    "Wind-Shear":     string;
    "Wind-Speed":     string;
}

export interface Info {
    City:      string;
    Country:   string;
    Elevation: string;
    IATA:      string;
    ICAO:      string;
    Latitude:  string;
    Longitude: string;
    Name:      string;
    Priority:  string;
    State:     string;
}

export interface Meta {
    "Cache-Timestamp": string;
    Timestamp:         string;
}

export interface Translations {
    Forecast:   TranslationsForecast[];
    "Max-Temp": string;
    "Min-Temp": string;
    Remarks:    Remarks;
}

export interface TranslationsForecast {
    Altimeter:    string;
    Clouds:       string;
    Icing:        string;
    Other:        string;
    Turbulance:   string;
    Visibility:   string;
    Wind:         string;
    "Wind-Shear": string;
}

export interface Remarks {
}

export interface Units {
    Altimeter:    string;
    Altitude:     string;
    Temperature:  string;
    Visibility:   string;
    "Wind-Speed": string;
}
