// Generated by https://quicktype.io

export interface MetarData {
    Altimeter:           string;
    "Cloud-List":        Array<string[]>;
    Dewpoint:            string;
    "Flight-Rules":      string;
    Info:                Info;
    Meta:                Meta;
    "Other-List":        any[];
    "Raw-Report":        string;
    Remarks:             string;
    "Remarks-Info":      RemarksInfo;
    "Runway-Vis-List":   any[];
    Speech:              string;
    Station:             string;
    Summary:             string;
    Temperature:         string;
    Time:                string;
    Translations:        Translations;
    Units:               Units;
    Visibility:          string;
    "Wind-Direction":    string;
    "Wind-Gust":         string;
    "Wind-Speed":        string;
    "Wind-Variable-Dir": any[];
}

export interface RemarksInfo {
    "Dew-Decimal":  string;
    "Temp-Decimal": string;
}

export interface Info {
    City:      string;
    Country:   string;
    Elevation: string;
    IATA:      string;
    ICAO:      string;
    Latitude:  string;
    Longitude: string;
    Name:      string;
    Priority:  string;
    State:     string;
}

export interface Meta {
    "Cache-Timestamp": string;
    Timestamp:         string;
}

export interface Translations {
    Altimeter:   string;
    Clouds:      string;
    Dewpoint:    string;
    Other:       string;
    Remarks:     { [key: string]: string };
    Temperature: string;
    Visibility:  string;
    Wind:        string;
}

export interface Units {
    Altimeter:    string;
    Altitude:     string;
    Temperature:  string;
    Visibility:   string;
    "Wind-Speed": string;
}
